local M = {}

local palette = {
    black = "Black",
    dark_blue = "DarkBlue",
    dark_green = "DarkGreen",
    dark_cyan = "DarkCyan",
    dark_red = "DarkRed",
    dark_magenta = "DarkMagenta",
    dark_yellow = "DarkYellow",
    light_grey = "LightGrey",
    dark_grey = "DarkGrey",
    light_blue = "LightBlue",
    light_green = "LightGreen",
    light_cyan = "LightCyan",
    light_red = "LightRed",
    light_magenta = "LightMagenta",
    light_yellow = "LightYellow",
    white = "White",
    background = "NONE"
}

-- Test

M.default_config = {
    ["WinSeparator"]            = { fg = palette.white, bg = palette.background },
    ["StatusLine"]              = { fg = palette.white, bg = palette.background, underdouble = true, sp = palette.white },
    ["StatusLineNC"]            = { fg = palette.light_grey, bg = palette.background, underline = true, sp = palette.white },
    ["StatusLineTerm"]          = { fg = palette.black, bg = palette.light_grey },
    ["StatusLineTermNC"]        = { fg = palette.black, bg = palette.dark_grey },
    ["Normal"]                  = { fg = palette.light_grey, bg = palette.background },
    ["TabLine"]                 = { fg = palette.light_grey, bg = palette.background, underline = true, sp = palette.white },
    ["TabLineFill"]             = { link = "TabLine" },
    ["TabLineSel"]              = { fg = palette.white, bg = palette.background, bold = true, underdouble = true, sp = palette.dark_grey },
    ["Visual"]                  = { reverse = true },
    ["VisualNOS"]               = { link = "Visual" },
    ["CursorLine"]              = {},
    -- ["ColorColumn"]             = { fg = "", bg = "" },
    -- ["Conceal"]                 = { fg = "", bg = "" },
    -- ["CurSearch"]               = { fg = "", bg = "" },
    -- ["Cursor"]                  = { fg = "", bg = "" },
    -- ["lCursor"]                 = { fg = "", bg = "" },
    -- ["CursorIM"]                = { fg = "", bg = "" },
    -- ["CursorColumn"]            = { fg = "", bg = "" },
    -- ["Directory"]               = { fg = "", bg = "" },
    -- ["DiffAdd"]                 = { fg = "", bg = "" },
    -- ["DiffChange"]              = { fg = "", bg = "" },
    -- ["DiffDelete"]              = { fg = "", bg = "" },
    -- ["DiffText"]                = { fg = "", bg = "" },
    -- ["DiffTextAdd"]             = { fg = "", bg = "" },
    -- ["EndOfBuffer"]             = { fg = "", bg = "" },
    -- ["TermCursor"]              = { fg = "", bg = "" },
    -- ["OkMsg"]                   = { fg = "", bg = "" },
    -- ["WarningMsg"]              = { fg = "", bg = "" },
    -- ["ErrorMsg"]                = { fg = "", bg = "" },
    -- ["StderrMsg"]               = { fg = "", bg = "" },
    -- ["StdoutMsg"]               = { fg = "", bg = "" },
    -- ["Folded"]                  = { fg = "", bg = "" },
    -- ["FoldColumn"]              = { fg = "", bg = "" },
    -- ["SignColumn"]              = { fg = "", bg = "" },
    -- ["IncSearch"]               = { fg = "", bg = "" },
    -- ["Substitute"]              = { fg = "", bg = "" },
    -- ["LineNr"]                  = { fg = "", bg = "" },
    -- ["LineNrAbove"]             = { fg = "", bg = "" },
    -- ["LineNrBelow"]             = { fg = "", bg = "" },
    -- ["CursorLineNr"]            = { fg = "", bg = "" },
    -- ["CursorLineFold"]          = { fg = "", bg = "" },
    -- ["CursorLineSign"]          = { fg = "", bg = "" },
    -- ["MatchParen"]              = { fg = "", bg = "" },
    -- ["ModeMsg"]                 = { fg = "", bg = "" },
    -- ["MsgArea"]                 = { fg = "", bg = "" },
    -- ["MsgSeparator"]            = { fg = "", bg = "" },
    -- ["MoreMsg"]                 = { fg = "", bg = "" },
    -- ["NonText"]                 = { fg = "", bg = "" },
    -- ["NormalFloat"]             = { fg = "", bg = "" },
    -- ["FloatBorder"]             = { fg = "", bg = "" },
    -- ["FloatShadow"]             = { fg = "", bg = "" },
    -- ["FloatShadowThrough"]      = { fg = "", bg = "" },
    -- ["FloatTitle"]              = { fg = "", bg = "" },
    -- ["FloatFooter"]             = { fg = "", bg = "" },
    -- ["NormalNC"]                = { fg = "", bg = "" },
    -- ["Pmenu"]                   = { fg = "", bg = "" },
    -- ["PmenuSel"]                = { fg = "", bg = "" },
    -- ["PmenuKind"]               = { fg = "", bg = "" },
    -- ["PmenuKindSel"]            = { fg = "", bg = "" },
    -- ["PmenuExtra"]              = { fg = "", bg = "" },
    -- ["PmenuExtraSel"]           = { fg = "", bg = "" },
    -- ["PmenuSbar"]               = { fg = "", bg = "" },
    -- ["PmenuThumb"]              = { fg = "", bg = "" },
    -- ["PmenuMatch"]              = { fg = "", bg = "" },
    -- ["PmenuMatchSel"]           = { fg = "", bg = "" },
    -- ["PmenuBorder"]             = { fg = "", bg = "" },
    -- ["PmenuShadow"]             = { fg = "", bg = "" },
    -- ["PmenuShadowThrough"]      = { fg = "", bg = "" },
    -- ["ComplMatchIns"]           = { fg = "", bg = "" },
    -- ["PreInsert"]               = { fg = "", bg = "" },
    -- ["ComplHint"]               = { fg = "", bg = "" },
    -- ["ComplHintMore"]           = { fg = "", bg = "" },
    -- ["Question"]                = { fg = "", bg = "" },
    -- ["QuickFixLine"]            = { fg = "", bg = "" },
    -- ["Search"]                  = { fg = "", bg = "" },
    -- ["SnippetTabstop"]          = { fg = "", bg = "" },
    -- ["SnippetTabstopActive"]    = { fg = "", bg = "" },
    -- ["SpecialKey"]              = { fg = "", bg = "" },
    -- ["SpellBad"]                = { fg = "", bg = "" },
    -- ["SpellCap"]                = { fg = "", bg = "" },
    -- ["SpellLocal"]              = { fg = "", bg = "" },
    -- ["SpellRare"]               = { fg = "", bg = "" },
    -- ["Title"]                   = { fg = "", bg = "" },
    -- ["Whitespace"]              = { fg = "", bg = "" },
    -- ["WildMenu"]                = { fg = "", bg = "" },
    -- ["WinBar"]                  = { fg = "", bg = "" },
    -- ["WinBarNC"]                = { fg = "", bg = "" },
}

M.setup = function(opts)
    local config = opts or M.default_config
    for group, colors in pairs(config) do
        vim.api.nvim_set_hl(0, group, colors)
        -- print(group .. " " .. vim.inspect(colors))
    end
end

M.setup()

return M
