vim.keymap.del("i", "<C-C>R", { buffer = 0 })
vim.keymap.del("i", "<C-C>L", { buffer = 0 })
vim.keymap.del("i", "<C-C>l", { buffer = 0 })
vim.keymap.del("i", "<C-C>c", { buffer = 0 })
vim.keymap.del("i", "<C-C>v", { buffer = 0 })
vim.keymap.del("i", "<C-C>p", { buffer = 0 })
vim.keymap.del("i", "<C-C>t", { buffer = 0 })
vim.keymap.del("i", "<C-C>s", { buffer = 0 })
vim.keymap.del("i", "<C-C>T", { buffer = 0 })
vim.keymap.del("i", "<C-C>o", { buffer = 0 })
vim.keymap.del("i", "<C-C>f", { buffer = 0 })
vim.keymap.del("i", "<C-C>k", { buffer = 0 })
vim.keymap.del("i", "<C-C>a", { buffer = 0 })

vim.keymap.set("i", "<C-S>R", [[<C-\><C-O>:call sqlcomplete#Map("resetCache")<CR><C-X><C-O>]], { buffer = 0, noremap = true, silent = true })
vim.keymap.set("i", "<C-S>L", [[<C-Y><C-\><C-O>:call sqlcomplete#Map("column_csv")<CR><C-X><C-O>]], { buffer = 0, noremap = true, silent = true })
vim.keymap.set("i", "<C-S>l", [[<C-\><C-O>:call sqlcomplete#Map("column_csv")<CR><C-X><C-O>]], { buffer = 0, noremap = true, silent = true })
vim.keymap.set("i", "<C-S>c", [[<C-\><C-O>:call sqlcomplete#Map("column")<CR><C-X><C-O>]], { buffer = 0, noremap = true, silent = true })
vim.keymap.set("i", "<C-S>v", [[<C-\><C-O>:call sqlcomplete#Map("view")<CR><C-X><C-O>]], { buffer = 0, noremap = true, silent = true })
vim.keymap.set("i", "<C-S>p", [[<C-\><C-O>:call sqlcomplete#Map("procedure")<CR><C-X><C-O>]], { buffer = 0, noremap = true, silent = true })
vim.keymap.set("i", "<C-S>t", [[<C-\><C-O>:call sqlcomplete#Map("table")<CR><C-X><C-O>]], { buffer = 0, noremap = true, silent = true })
vim.keymap.set("i", "<C-S>s", [[<C-\><C-O>:call sqlcomplete#Map("sqlStatement\\w*")<CR><C-X><C-O>]], { buffer = 0, noremap = true, silent = true })
vim.keymap.set("i", "<C-S>T", [[<C-\><C-O>:call sqlcomplete#Map("sqlType\\w*")<CR><C-X><C-O>]], { buffer = 0, noremap = true, silent = true })
vim.keymap.set("i", "<C-S>o", [[<C-\><C-O>:call sqlcomplete#Map("sqlOption\\w*")<CR><C-X><C-O>]], { buffer = 0, noremap = true, silent = true })
vim.keymap.set("i", "<C-S>f", [[<C-\><C-O>:call sqlcomplete#Map("sqlFunction\\w*")<CR><C-X><C-O>]], { buffer = 0, noremap = true, silent = true })
vim.keymap.set("i", "<C-S>k", [[<C-\><C-O>:call sqlcomplete#Map("sqlKeyword\\w*")<CR><C-X><C-O>]], { buffer = 0, noremap = true, silent = true })
vim.keymap.set("i", "<C-S>a", [[<C-\><C-O>:call sqlcomplete#Map("syntax")<CR><C-X><C-O>]], { buffer = 0, noremap = true, silent = true })
